### PR TITLE
Added support for dynamic authentication

### PR DESCRIPTION
**Pull request by Na-ru-to4170**

### CODE REVIEW

**Comment by yesoreyeram** [comment]
@Na-ru-to4170 Good one.

BTW, you don't need to commit files in dist folder. Also in your PR , I don't see an option to specify `tokenAuth` details in config editor.  I assume this is a work in progress from your side.

**Comment by Na-ru-to4170** [comment]
Thanks for quick reply..
I will remove it from the dist folder.
My question is that if we can add it in plugin.json itself then anybody can inject their values according to there need then is there any need to have a config editor for it ?

**Comment by yesoreyeram** [comment]
Yes you need to have config editor. you can't edit the plugin.json directly.

**Comment by Na-ru-to4170** [comment]
ok got it.
Will give a try to add in editor mode.
One last question.. will this suffice for now or you think I need to add something extra?

**Comment by yesoreyeram** [comment]
Thats all i think. Sensitive information you need to read rom SecureJsonData and not from JsonData

**Comment by Na-ru-to4170** [comment]
Done.. Can you approve it? :)

**Comment by yesoreyeram** [comment]
This won't work without config editor to pass the fields.

**Comment by Na-ru-to4170** [comment]
Hi
Can you tell me how to test this in my local ?

**Comment by yesoreyeram** [comment]
Hi @Na-ru-to4170  - Can you take latest from https://github.com/yesoreyeram/grafana-infinity-datasource/tree/feature/token-authentication and work if you are interested. I have setup a base for token authentication. ( working version )

**Comment by Na-ru-to4170** [comment]
Sure @yesoreyeram  let me give a try.. Thanks :)

**Comment by Na-ru-to4170** [comment]
hi @yesoreyeram  I am having difficulty with these type-scripts.
Can you point to right doc where I can learn type-script.. then I might be able to contribute here

**Comment by yesoreyeram** [comment]
As the plugin is being migrated into the backend to support more features, I am closing this PR for now. Thank you very much for the efforts and feedback.

**Pull request closed without merging**
